services:
  database:
    container_name: stonemark-db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: stonemark
      PGDATA: /var/lib/postgresql/data
    volumes:
      - stonemark-db:/var/lib/postgresql
    ports:
      - "5440:5432"
    networks:
      - stonemark-network
    restart: unless-stopped

  minio:
    container_name: stonemark-minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - stonemark-network

networks:
  stonemark-network:
    driver: bridge

volumes:
  stonemark-db:
    driver: local
  minio-data:
    driver: local
